services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-academy-api_c
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - ./db:/rails/db

    env_file:
      - .env.development

    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: my-academy-app_c
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    environment:
      PORT: 3001
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_volume_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_volume_data:
  db:
